In [2]:
import numpy as np

In [3]:
p = int(input())

5


In [4]:
k = int(input())

9


In [62]:
x = np.random.random(p).reshape(p,1)

In [63]:
y = np.eye(p)

In [64]:
a = y * x

In [65]:
u = np.random.random((p,k))

In [66]:
v = np.random.random((k,p))

In [67]:
c = np.eye(k)

In [68]:
def woodbury(a, u, v):
    a1 = np.linalg.inv(a)
    f = np.linalg.inv(c + v @ a1 @ u)
    return a1 - a1 @ u @ f @ v @ a1

In [69]:
woodbury(a, u, v)

array([[  72.56154734,   30.69393497,    1.67035358,  -47.56901829,
         -58.91481626],
       [ 102.31662041,   50.14723361,    4.09959514,  -69.89669862,
         -91.2433271 ],
       [   2.96844079,    2.6695574 ,    1.19288055,   -2.8198572 ,
          -4.62052504],
       [  17.41708204,    7.5817155 ,    0.56448436,  -10.73142217,
         -15.36574206],
       [-202.55885636,  -94.96422087,   -7.87383032,  136.35090705,
         177.20819657]])

In [70]:
def realwoodbury(a, u, v):
    return np.linalg.inv(a + u @ v)

In [71]:
realwoodbury(a, u, v)

array([[  72.56154734,   30.69393497,    1.67035358,  -47.56901829,
         -58.91481626],
       [ 102.31662041,   50.14723361,    4.09959514,  -69.89669862,
         -91.2433271 ],
       [   2.96844079,    2.6695574 ,    1.19288055,   -2.8198572 ,
          -4.62052504],
       [  17.41708204,    7.5817155 ,    0.56448436,  -10.73142217,
         -15.36574206],
       [-202.55885636,  -94.96422087,   -7.87383032,  136.35090705,
         177.20819657]])

In [2]:
import numpy as np 
import matplotlib 
A = np.array([[3,0], [0,-2]]) 
Lv, Sig, Rv = np.linalg.svd(A) 
print(Lv, Rv)

[[1. 0.]
 [0. 1.]] [[ 1.  0.]
 [-0. -1.]]
